### ISSUE TITLE
Docker - publication de l'image docker au niveau du registry github

### ISSUE THREAD

**Issue by mborne** [IGNF/apicarto#73]
Ceci facilitera les premières expérimentations pour déploiement en environnement kubernetes.

**Comment by mborne** [comment]
@vinsag , je peux te laisser intégrer ceci stp : 

https://github.com/mborne/apicarto/blob/master/.github/workflows/docker-publish.yml

Remarque : La partie suivante n'est pas indispensable (test sur dépôt personnel pour avoir des images pour raspberry & x86)

```yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
```
